### ISSUE TITLE
Use template example-app for CI

### ISSUE THREAD

**Issue by oskarth** [zkmopro/mopro#117]
# Problem

We currently use the more "heavy" https://github.com/oskarth/mopro/tree/main/mopro-ios and https://github.com/oskarth/mopro/tree/main/mopro-android for CI.

It'd be good to instead use the example app for this https://github.com/oskarth/mopro/tree/main/templates/mopro-example-app

## Suggested solution

- Change CI to use template example app
- Remove legacy mopro-ios and mopro-android folders
- Optionally: also use mopro-cli to create example app instead of using the template itself (later on this might be non-executable code)

**Comment by vivianjeng** [comment]
fixed by https://github.com/zkmopro/mopro-android
https://github.com/zkmopro/mopro-ios
https://github.com/zkmopro/mopro/pull/135
