### ISSUE TITLE
Publish ark-zkey module as a library on Crate.io

### ISSUE THREAD

**Issue by seemenkina** [zkmopro/mopro#131]
## Problem

The `mopro` project currently works under a patch to the `wasmer` library. This patch causes a conflict and overrides dependencies when using `mopro` as a submodule if `wasmer` is also used in the other project. At the same time `ark-zkey` module does not require a `wasmer`, but because it is part of the `mopro` project you have to connect the whole project.  

## Suggested solution

To address this issue, I suggest isolating `ark-zkey`  module as a library and publishing it separately. It provides easy use of its functionality to everyone.

**Comment by rymnc** [comment]
cc: @vivianjeng as per recommendation from Oskar :)

**Comment by vivianjeng** [comment]
sorry for the late reply
let me know if it works for you
https://crates.io/crates/ark-zkey

**Comment by seemenkina** [comment]
Hey @vivianjeng, thank you so much! I'll check in a while

cc: @rymnc

**Comment by oskarth** [comment]
Seems to have been fixed, https://github.com/vacp2p/zerokit/pull/251

Thanks everyone!
