### ISSUE TITLE
Initial Android support

### ISSUE THREAD

**Issue by oskarth** [zkmopro/mopro#17]
# Problem

mopro doesn't run on Android. We want it to run Android, and it shouldn't be too much work to get basic support.

See https://github.com/oskarth/mopro/issues/16 for other platforms

# Notes

Might need to start with a subset of Android platforms, as some older versions might need additional work.

Some equivalent of Cocoapods would be useful.

# Acceptance criteria

- [x] Kotlin tests mirroring Swift tests in https://github.com/oskarth/mopro/tree/main/mopro-ffi/tests/bindings
- [ ] Library equivalent to Cocoapods that bundles
- [x] With example app similar to iOS
- [x] Updated build scripts for Android
- [x] Updated basic docs

**Comment by oskarth** [comment]
We also want cleaner solution to this:

https://github.com/oskarth/mopro/blob/main/.github/workflows/build-and-test.yml#L31-L32

**Comment by oskarth** [comment]
@vivianjeng is there something missing for this? I haven't played with Android setup much, but to me main things that aren't clear are (1) CI (2) Lib/distribution on Android

**Comment by vivianjeng** [comment]
1) The tests are mirrored: https://github.com/oskarth/mopro/tree/main/mopro-ffi/tests/bindings
    Except for new tests added (msm, rsa2)
    but keccak and rsa also occurs error in CI but haven't been fixed: `java.lang.OutOfMemoryError: Java heap space`
2) haven't started yet

**Comment by oskarth** [comment]
I think we can close this issue now, makes more sense to have specific issues for improved Android support now I think
