### ISSUE TITLE
Support Multiple Circuits

### ISSUE THREAD

**Issue by doutv** [zkmopro/mopro#171]
Current `mopro-config.toml` only support one circuit. Is it possible to support multiple circuits?

**Comment by vivianjeng** [comment]
You can try to use https://github.com/zkmopro/mopro/blob/56290d888af441d0cd74f648d9c1d25686b9a50e/mopro-core/src/middleware/circom/mod.rs#L294
so you can init 2 `moproCircom` state 
and put different wasm/zkey inside

**Comment by vivianjeng** [comment]
https://github.com/zkmopro/mopro-ios/blob/e34c62e91924e4995e1d924df4cd03ce32f89120/MoproKit/Example/MoproKit/KeccakSetupViewController.swift#L124
https://github.com/zkmopro/mopro-ios/blob/e34c62e91924e4995e1d924df4cd03ce32f89120/MoproKit/Example/MoproKit/KeccakSetupViewController.swift#L169
