### ISSUE TITLE
Scripts: Passing Features to build scripts

### ISSUE THREAD

**Issue by ElusAegis** [zkmopro/mopro#177]
Allow to pass multiple rust compilation features from the config file to the build scripts.

### Motivation 

To allow to use of experimental features, which exist right now for Circom, however currently can not be used.

### Source 

>               I suppose there will be more than one feature here
> e.g. `"circom gpu-benchmarks"`
> but it is also good to have this here

_Originally posted by @vivianjeng in https://github.com/zkmopro/mopro/pull/149#discussion_r1627093099_

**Comment by vimwitch** [comment]
Closing as unnecessary, apps can now directly enable/disable features.
