### ISSUE TITLE
Config: Have a section for a adapter specific configs

### ISSUE THREAD

**Issue by ElusAegis** [zkmopro/mopro#178]
Different adapters need different config entries. Thus the a need to make some entries to be only required for a particular adapter type.

> I guess these options are not needed for Halo2. 
> Should we remove dylib and witness from this config?

_Originally posted by @oskarth in https://github.com/zkmopro/mopro/pull/149#discussion_r1625339482_

**Comment by vimwitch** [comment]
Closing, config logic is implemented in rust now and is adapter specific
