### ISSUE TITLE
Mopro Cli v0.1.0

### ISSUE THREAD

**Issue by vivianjeng** [zkmopro/mopro#234]
# Problem
A cli like `circom`, foundry, `create-react-app`... is helpful for developers getting started with a new project.

## Details
- create a `mopro-cli` directory including the following commands
1. `mopro init`: create an example rust project following the tutorial: [Rust Setup](https://zkmopro.org/docs/getting-started/rust-setup)
   - (Optional) Let user input a project name
   - (Optional) Let user specify proving systems
   - (Optional) Let user input circuits path
2. `mopro build`: export `MoproiOSBindings`, `MoproAndroidBindings`
3. `mopro create`: create the mobile app itself
   - Options: `platforms`
       - `swift` (template: [iOS Setup](https://zkmopro.org/docs/getting-started/ios-setup))
       - `kotlin` (template: [Android Setup](https://zkmopro.org/docs/getting-started/android-setup)
       - `react-native` (template: React Native Setup)

## Acceptance criteria
Make sure `mopro init`, `mopro build`, `mopro create` works and the apps work

## Next steps (optional)
- Documentation:
**Getting started** with the cli
And move the current setups to **Tutorial** section

**Comment by oskarth** [comment]
For reference, here's the previous issue https://github.com/zkmopro/mopro/issues/77 that was addressed with `mopro-cli`

Documentation here https://zkmopro.org/docs/0.0.1/mopro-cli

Example usage here https://www.loom.com/share/6ff382b0497c47aea9d0ef8b6e790dd8

**Comment by vivianjeng** [comment]
`mopro init` is done #235 
`mopro build` is opened #237

**Comment by vivianjeng** [comment]
`mopro create` is done #245 (for iOS and Android)
TODO: react-native and flutter
