### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by oskarth** [zkmopro/mopro#43]
## Problem

A lot of projects want React Native library. We should support this.

## Notes

With native modules we should be able to bind the Swift and Kotlin to a basic React Native library.

See https://reactnative.dev/docs/native-modules-intro

## Acceptance criteria

Basic React Native library support.

**Comment by oskarth** [comment]
Seems like we need an Obj C bridging header. Something like this:

Swift:

```
// MoproCircom+ReactNative.swift
import Foundation

extension MoproCircom {
    @objc func generateProofWithCallback(circuitInputs: [String: [String]], callback: @escaping RCTResponseSenderBlock) {
        do {
            let result = try generateProof(circuitInputs: circuitInputs)
            // Convert `GenerateProofResult` to a dictionary or array if necessary
            callback([NSNull(), result.toDictionary()])
        } catch let error {
            callback([error.localizedDescription, NSNull()])
        }
    }

    // Add similar methods for `setup` and `verifyProof`
}
```

Obj C:

```
// MoproCircomBridge.m
#import "React/RCTBridgeModule.h"

@interface RCT_EXTERN_MODULE(MoproCircom, NSObject)
RCT_EXTERN_METHOD(generateProofWithCallback:(NSDictionary *)circuitInputs callback:(RCTResponseSenderBlock)callback)
// Add similar extern declarations for `setup` and `verifyProof`
@end
```

JS:

```
import { NativeModules } from 'react-native';

const { MoproCircom } = NativeModules;

MoproCircom.generateProofWithCallback(circuitInputs, (error, result) => {
  if (error) {
    console.error(error);
  } else {
    console.log(result);
  }
});

// Add similar calls for `setup` and `verifyProof`
```

**Comment by Meyanis95** [comment]
@oskarth I am Assigning this one to me for the moment. 
I'm working on an RN library setup, that I'll push in our GitHub org once having something working. Once the specs and objc bridge specs are refined, we could add it to Mopro settings if it's wanted/needed by Mopro.
WDYT?

**Comment by oskarth** [comment]
Sounds great!

**Comment by Meyanis95** [comment]
Update: 

I have a working bridge that you'll be able to find [here](https://github.com/anon-aadhaar/anon-aadhaar-react-native).
It's a bit tricky but possible. 

- [The objc swift wrapper](https://github.com/anon-aadhaar/anon-aadhaar-react-native/blob/fe0d932ca9e8249eac4063939d1189f72ded8e66/ios/mopro.swift#L401)
- [The objc bridge](https://github.com/anon-aadhaar/anon-aadhaar-react-native/blob/fe0d932ca9e8249eac4063939d1189f72ded8e66/ios/MoproCircomBridge.m#L14)

You'll find a working example of the `complex-circuit-100k` circuit.

<img width="760" alt="image" src="https://github.com/oskarth/mopro/assets/67648863/9fb2becb-c3ef-4eeb-8b20-b668a3ce3138">

Next steps: 
- Clean the repo
- Find ways to automatize this bridging to have a clean workflow with the CLI
- Try to run it on device
- Try with AA circuits

**Comment by oskarth** [comment]
Awesome!

**Comment by oskarth** [comment]
See https://github.com/anon-aadhaar/anon-aadhaar-react-native/commit/d6443316200cd3e1f17ad2679458cc6e6e9fe1f2 for latest React Native WIP integration

**Comment by oskarth** [comment]
We want to take this RN WIP integration above and:

1) Add to mopro-cli as platform option
2) Integrate into example app template
3) Basic docs about usage

**Comment by vivianjeng** [comment]
I built this example app https://github.com/zkmopro/react-native-app
Next steps:
- write down documentation
   - how to setup from a new project
   - how to integrate with existing react native project
- try to support snarkjs in browser
- benchmark the performance
- (cli to init a react native project)
